### ISSUE TITLE
Add pacakge to Packagist

### ISSUE THREAD

**Issue by markuspoerschke** [comsolit/easy_googlemap#10]
Integrate this GitHub repository with Packagist.org to allow installation using Packagist pacakge by running following command: `composer require comsolit/easy_googlemap`.

Also the according setting in the TYPO3 Extension Repository must be set to display a hint, that this package can be installed using Packagist.

The officially recommended way it to install extensions from Packagist directly:

> Once you added a composer.json file, it is highly recommended to register your extensions on Packagist.
>
> It is also recommended to include extensions directly from Packagist instead of using this Composer repository. For example, better require georgringer/news than typo3-ter/news, if you want the News extension in your composer installation.

– [TYPO3 Extension Composer Repository](https://composer.typo3.org/)

**Comment by ghost** [comment]
Here it is https://packagist.org/packages/comsolit/easy_googlemap
