### ISSUE TITLE
Custom pin selection not working

### ISSUE THREAD

**Issue by valifyde** [comsolit/easy_googlemap#11]
I get the following error (file from filelist)

	
1: The destination (path-to-project.../typo3/public/uploads/tx_easygooglemap) or the source file (path-to-project.../typo3/public/fileadmin/content/ml/Meta/Anfahrt/singlemarker.png) does not exist. (tx_easygooglemap_domain_model_location:1:icon)

The file exists definitively :-)

Version: "comsolit/easy_googlemap": "^3.0"
TYPO3-Version: 9.5.11

**Comment by tecjam** [comment]
Hi @valifyde 

This issue should be fixed in version 3.0.2 - Please give it a try and let us know if the issue persists.
Version 3.0.2 should be in the TER in the next few days. Until then feel free to update via composer.

https://packagist.org/packages/comsolit/easy_googlemap
