### ISSUE TITLE
Wrong float latitude/longitude

### ISSUE THREAD

**Issue by johanneshahn** [comsolit/easy_googlemap#3]
I found a bug,
where in german the float latitude/longitude is localized and the location marker is set in wrong place.
Take a look here: http://php.net/manual/en/language.types.float.php#58824

Example:
out put in english "48.5115188" -> works
out put in german "48,5115188" -> result is wrong position on google map

My solution was to change the Fluid Template "Resources/Private/Templates/Location/List.html"

from:
`latitude: parseFloat("<f:format.raw value="{location.latitude}" /></f:format.number>"),`

to:

`latitude: parseFloat("<f:format.number decimalSeparator="." thousandsSeparator="." decimals="7" >{location.latitude}</f:format.number>"),`

**Comment by ghost** [comment]
What did you mean with out put in german?
How can we reproduce this?

**Comment by johanneshahn** [comment]
Hi,
u can set it in the TS like

```
config{
        sys_language_uid = 0
        language = de
        locale_all = de_DE.UTF8
        linkVars = L
        sys_language_overlay = 1 
}
```

with output i mean the html source output eg. Javascript output

**Comment by ghost** [comment]
I'm sorry we can not reproduce this problem and we have many TYPO3 Setups in German with easy_googlemap and I know many peoples in german and switzerland they have'n a problem there.

Maybe your problem is something other, put if it helps you you can overwrite the extension template.
