### ISSUE TITLE
I cant to customize templates and layout

### ISSUE THREAD

**Issue by gvv1401** [comsolit/easy_googlemap#6]
**In constants.txt I have next lines (new pathes):**
plugin.tx_easygooglemap {
	view {
		layoutRootPath   = EXT:t3web_site/Resources/Private/Templates/Extensions/Easygooglemap/Layouts/
		templateRootPath = EXT:t3web_site/Resources/Private/Templates/Extensions/Easygooglemap/Templates/
		partialRootPath  = EXT:t3web_site/Resources/Private/Templates/Extensions/Easygooglemap/Templates/
	}
}

**On FE (via DebuggerUtility::var_dump) I see next values:**
      templateRootPath => 'EXT:t3web_site/Resources/Private/Templates/Extensions/Easygooglemap/Template
         s/' (78 chars)
      partialRootPath => 'EXT:t3web_site/Resources/Private/Templates/Extensions/Easygooglemap/Template
         s/' (78 chars)
      layoutRootPath => 'EXT:t3web_site/Resources/Private/Templates/Extensions/Easygooglemap/Layouts/' (

**My Layouts/Default.html:**
!!!===============DUMMY LINE=========================!!!
<f:render section="main" />

I cant see my dummy chars on FE ("===================")! Why?

Easy_goolemap version: 1.2.10
TYPO3 version: 7.6.14
PHP version: 7.0.13

**Comment by ghost** [comment]
Hi gvv1401,
an extraordinary name you have.

I'm not sure but you put the "dummy line" outside of the main section
maybe this is the reason

Cheers Lars

**Comment by gvv1401** [comment]
No, Lars. I put "dummy line" instead of div class="tx-easy-googlemap", but this DIV always exist.
