### ISSUE TITLE
Problems with negativ Longitude values (< 0 and > -1)

### ISSUE THREAD

**Issue by gonzalesindie** [comsolit/easy_googlemap#7]
I am currently using the "EasyGoogleMap"-Extension (V2.0.0) on Typo3 (V7.6.26) and I found a little bug. I tried to add a location in Brighton (Longitude: -0.1357030 / Latitude: 50.8203296) but the extension always changes the Longitude value to 0.1357030 (from negative to positive). It seems that the extension is not capable of processing Longitude values < 0 and > -1.

**Comment by ghost** [comment]
Thank you for the information, @condoridiomas.

This issue has been fixed in version 2.0.1 for TYPO3 versions 7.x and 8.x and in version 3.0.1 for TYPO3 version 9.x.
