### ISSUE TITLE
Infotext doen`t work

### ISSUE THREAD

**Issue by holkraft** [comsolit/easy_googlemap#8]
Hiya,
we are using easy_googlmap  2.0 at a typo3-Installation with version 7.6.29 and run into an issue. The marker are shown in the infomap at the frontend.  
We added also an infotext and ckecked the "Infobox" checkbox. But the mouspinter at the frontend is allways the grabbing hand and we can move only the whole map. If we hoover iver the icon the pointer still is the grabing hand, not the pointing finger. So the infotext can't be open by the visitor of our page. 
Do you have any suggestion?
Regards Holger

**Comment by nicolez9911** [comment]
Hi Holger
We had the same problem. We could solve it with a little CSS:
.gmnoprint {
    display: block;
}
Cheers, Nicole

**Comment by holkraft** [comment]
Hi Nicole,
thanks for your fast reply. 
As you suggestedd I added the information to the css and the problem is solved. Great!

Regards, Holger
