### ISSUE TITLE
default value for column infotext

### ISSUE THREAD

**Issue by rtoenjes** [comsolit/easy_googlemap#9]
Installing easy_googlemaps with MySQL 5.7 (or earlier?) doesn't work because of `infotext text DEFAULT '',` in ext_tables.sql.

Zitating https://dev.mysql.com/doc/refman/5.7/en/blob.html:
> BLOB and TEXT columns cannot have DEFAULT values.

**Comment by ghost** [comment]
@rtoenjes Thanks for the information.

This issue has been fixed in versions 2.0.1 (for TYPO3 version 7.x and 8.x) and 3.0.1 (for TYPO3 version 9.x).
